# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-12-04 06:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formattedcontent', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Content',
        ),
        migrations.RenameField(
            model_name='formattedcontent',
            old_name='content',
            new_name='tagContent',
        ),
        migrations.AddField(
            model_name='formattedcontent',
            name='htmlContent',
            field=models.CharField(default='', max_length=5000),
        ),
    ]
