# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-18 22:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0002_auto_20171018_2135'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='generic',
            name='preguntas',
        ),
        migrations.AddField(
            model_name='pregunta',
            name='encuesta',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='builder.Generic'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='answer',
            field=models.CharField(choices=[('si', 'Si'), ('no', 'No')], max_length=2),
        ),
    ]
