# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0003_auto_20171018_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pregunta',
            name='encuesta',
        ),
        migrations.RemoveField(
            model_name='template',
            name='html',
        ),
        migrations.RemoveField(
            model_name='template',
            name='user',
        ),
        migrations.AddField(
            model_name='template',
            name='name',
            field=models.CharField(default='', max_length=128),
        ),
        migrations.DeleteModel(
            name='Generic',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
