# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-29 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200, verbose_name='Nombre:')),
                ('fecha_publ', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='fecha de creacion:')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=200, verbose_name='Pregunta:')),
                ('respuesta', models.CharField(max_length=1000, verbose_name='Respuesta:')),
                ('faq', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='faqs.Categoria')),
            ],
        ),
    ]
