# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 21:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faqs.Faq'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='faq',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faqs.Faq'),
        ),
    ]
