# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 00:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.TextField(max_length=1000, verbose_name='Respuesta:'),
        ),
    ]
