# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-18 05:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0002_auto_20171101_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreguntaFaq',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pregunta', models.CharField(max_length=100, verbose_name='Pregunta:')),
                ('respuesta', models.TextField(max_length=250, verbose_name='Respuesta:')),
                ('faq', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faqs.Faq')),
                ('tema', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='faqs.Categoria')),
            ],
            options={
                'ordering': ['id'],
            },
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='faq',
        ),
        migrations.RemoveField(
            model_name='pregunta',
            name='tema',
        ),
        migrations.DeleteModel(
            name='Pregunta',
        ),
    ]
