# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-30 00:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0003_auto_20171030_0043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='pregunta',
            field=models.CharField(max_length=100, verbose_name='Pregunta:'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='respuesta',
            field=models.TextField(max_length=250, verbose_name='Respuesta:'),
        ),
    ]
