# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-11-01 01:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('faqs', '0005_auto_20171101_0109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['id']},
        ),
        migrations.AlterModelOptions(
            name='pregunta',
            options={'ordering': ['id']},
        ),
    ]
