# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-30 01:15
from __future__ import unicode_literals

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tab_id', models.UUIDField(default=uuid.uuid4, editable=False, verbose_name='Id del tab')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Titulo del tab')),
                ('title_style', models.TextField(blank=True, null=True, verbose_name='Estilos del titulo')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Contenido del tab')),
                ('content_style', models.TextField(blank=True, null=True, verbose_name='Estilos del contenido')),
                ('width', models.CharField(blank=True, default='50', max_length=50, null=True, verbose_name='Ancho (%)')),
                ('height', models.CharField(blank=True, default='30', max_length=50, null=True, verbose_name='Alto (px)')),
            ],
        ),
    ]
