# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 20:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='border_color',
            field=models.TextField(blank=True, null=True, verbose_name='Color del borde'),
        ),
        migrations.AddField(
            model_name='tab',
            name='border_radius',
            field=models.TextField(blank=True, null=True, verbose_name='Radio del borde'),
        ),
        migrations.AddField(
            model_name='tab',
            name='border_style',
            field=models.TextField(blank=True, null=True, verbose_name='Definir tipo de borde'),
        ),
        migrations.AddField(
            model_name='tab',
            name='content_color',
            field=models.TextField(blank=True, null=True, verbose_name='Color del contenido'),
        ),
        migrations.AddField(
            model_name='tab',
            name='style',
            field=models.TextField(blank=True, null=True, verbose_name='Extra CSS'),
        ),
    ]
