# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-31 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0002_auto_20171031_2010'),
    ]

    operations = [
        migrations.AddField(
            model_name='tab',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='tab',
            name='tabs',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='brothers', to='tab.Tab'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='content',
            field=models.TextField(blank=True, null=True, verbose_name='Contenido'),
        ),
        migrations.AlterField(
            model_name='tab',
            name='width',
            field=models.CharField(blank=True, default='100', max_length=50, null=True, verbose_name='Ancho (%)'),
        ),
    ]
