# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 01:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0003_auto_20171031_2104'),
    ]

    operations = [
        migrations.CreateModel(
            name='TabContainer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nombre del container')),
                ('children', models.IntegerField(default=0)),
            ],
        ),
        migrations.RemoveField(
            model_name='tab',
            name='tabs',
        ),
    ]
