# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0005_auto_20171101_0325'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab',
            name='parent',
        ),
        migrations.AddField(
            model_name='tab',
            name='partner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tabs', to='tab.Tab'),
        ),
    ]
