# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0006_auto_20171101_0535'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tab',
            name='partner',
        ),
        migrations.AddField(
            model_name='tab',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tab.TabContainer'),
        ),
    ]
