# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 05:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0007_auto_20171101_0549'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabcontainer',
            name='children',
            field=models.IntegerField(default=1),
        ),
    ]
