# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0008_auto_20171101_0558'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabcontainer',
            name='name',
            field=models.CharField(blank=True, max_length=100, verbose_name='Nombre del container'),
        ),
    ]
