# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-01 06:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0009_auto_20171101_0609'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tabcontainer',
            old_name='children',
            new_name='children_amount',
        ),
    ]
