# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-14 22:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0010_auto_20171101_0619'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabcontainer',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre del container'),
        ),
    ]
