# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-23 14:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0011_auto_20171114_1809'),
        ('tab', '0011_auto_20171102_1256'),
    ]

    operations = [
    ]
