# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 12:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tab', '0012_merge_20171123_1422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tabcontainer',
            name='children_amount',
            field=models.IntegerField(default=1, verbose_name='Cantidad de pestañas'),
        ),
    ]
