# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 02:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BreadcrumbsContent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('url', models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name='BreadcrumbsLevels',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('levels', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='breadcrumbscontent',
            name='breadcrumb',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='breadcrumbs.BreadcrumbsLevels'),
        ),
    ]
