# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 03:07
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BreadcrumbsLevels',
            new_name='Breadcrumb',
        ),
        migrations.RenameModel(
            old_name='BreadcrumbsContent',
            new_name='BreadcrumbContent',
        ),
    ]
