# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-12-07 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('breadcrumbs', '0002_auto_20171206_2307'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='breadcrumb',
            name='levels',
        ),
        migrations.AddField(
            model_name='breadcrumb',
            name='title',
            field=models.CharField(default='Breadcrumb', max_length=30),
        ),
    ]
