# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_publ',
            field=models.DateTimeField(null=True, verbose_name='fecha de publicación'),
        ),
    ]
