# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 16:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0002_auto_20171018_1613'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pregunta',
            name='fecha_publ',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='fecha de publicación'),
        ),
    ]
