# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-10-18 21:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('encuestas', '0003_auto_20171018_1653'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opcion',
            name='texto_opcion',
            field=models.CharField(max_length=200, verbose_name='Opción:'),
        ),
        migrations.AlterField(
            model_name='pregunta',
            name='texto_pregunta',
            field=models.CharField(max_length=200, verbose_name='Pregunta:'),
        ),
    ]
