# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-19 19:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('builder', '0004_auto_20171019_1953'),
        ('encuestas', '0004_auto_20171018_2142'),
    ]

    operations = [
        migrations.AddField(
            model_name='pregunta',
            name='template',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.Template'),
        ),
    ]
