# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-02 10:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('builder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Captcha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(null=True)),
                ('template', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='builder.Template')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
