# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2017-11-16 04:44
from __future__ import unicode_literals

from django.db import migrations, models
import servecaptcha.utils.random_string


class Migration(migrations.Migration):

    dependencies = [
        ('captcha_pattern', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='captcha',
            name='private_key',
            field=models.CharField(default=servecaptcha.utils.random_string.alphanumeric, max_length=64, unique=True),
        ),
        migrations.AddField(
            model_name='captcha',
            name='public_key',
            field=models.CharField(default=servecaptcha.utils.random_string.alphanumeric, max_length=64, unique=True),
        ),
    ]
